### ISSUE TITLE
Study guide API not working

### ISSUE THREAD

**Issue by therbom** [DutchCodeGeeks/MATA-PHP#17]
Hi, I'm trying to use your API to get the study guides available on our school's server. The login process works, as it correctly returns my real name, but getStudyGuideList() returns an empty array. I can verify that they exist if I login normally to https://mata-zaamnoord.magister.net.

Output of var_dump($session):

``` php
object(mataphp\Session)#1 (4) {
  ["school"]=>
  object(mataphp\School)#2 (2) {
    ["name"]=>
    string(8) "Damstede"
    ["url"]=>
    string(27) "mata-zaamnoord.magister.net"
  }
  ["userId"]=>
  int(5394)
  ["sessionId"]=>
  string(13) "5394440b8e221"
  ["realName"]=>
  string(12) "Marco Brohet"
}
```

Output of var_dump(mataphp\getStudyGuideList($session)):

``` php
array(0) {
}
```

PHP error log:

```
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Notice:  Use of undefined constant STDERR - assumed 'STDERR' in ***/api.php on line 6
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Strict Standards:  Non-static method mataphp\\Mataphp::encodeURIComponent() should not be called statically in ***/api.php on line 160
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Strict Standards:  Non-static method mataphp\\Mataphp::curlget() should not be called statically in ***/api.php on line 160
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Warning:  curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in ***/api.php on line 130
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Strict Standards:  Non-static method mataphp\\Mataphp::curlget() should not be called statically in ***/api.php on line 224
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Warning:  curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in ***/api.php on line 130
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Strict Standards:  Non-static method mataphp\\Mataphp::curlget() should not be called statically in ***/api.php on line 168
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Warning:  curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in ***/api.php on line 130
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Warning:  Invalid argument supplied for foreach() in ***/api.php on line 171
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Strict Standards:  Non-static method mataphp\\Mataphp::curlget() should not be called statically in ***/api.php on line 187
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Warning:  curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in ***/api.php on line 130
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Warning:  Invalid argument supplied for foreach() in ***/api.php on line 190
[Sun Jun 08 13:07:55 2014] [error] [client ***] PHP Warning:  file_exists(): open_basedir restriction in effect. File(.mata-php.api.cookie.5394440b8e221) is not within the allowed path(s): (***:/tmp:/var/tmp:/usr/local/lib/php/) in ***/api.php on line 33
```

**Comment by KeizerDev** [comment]
Is there already a documentation repo?
I'm busy porting making a Java(Android app) client and that would speed up the process a lot!

Btw: I've written a documentation myself but I really want to see if you guys have found new things I didn't notice.

Always nice to share some knowledge,
Thanks

**Comment by lesander** [comment]
@KeizerDev People have moved on to Magister 6 and JavaScript / NodeJS: https://github.com/simplyGits/MagisterJS

**Comment by tkon99** [comment]
Well, we thought it wasn't needed as
1 - It's pretty easy to view through network log
2 - The libs got good documentation

**Comment by KeizerDev** [comment]
True that. But if you want to see how "cijfers" works for example, it's
pretty nested and it is quite annoying to have to login on Magister again
and check out the Network log to see how something work.
If we instead of that just made one easy documentation repo, it wil be a
lot easier for everyone to make their Magister module or program and port
it to different languages like Python, Java, Objective-C, etc.
Op 16 mrt. 2015 21:31 schreef "Thomas Konings" <notifications@github.com>:

**Comment by tkon99** [comment]
You could create a new file in:
https://github.com/DutchCodeGeeks/MagisterHub?files=1
And send us a pull request.

Op ma 16 mrt. 2015 22:12 schreef KeizerDev <notifications@github.com>:

**Comment by lieuwex** [comment]
@KeizerDev Go ahead, I'm too busy right now. :P
