### ISSUE TITLE
Samenwerking

### ISSUE THREAD

**Issue by ghost** [DutchCodeGeeks/MATA-PHP#19]
Hallo DCG,
Ik ben bezig met een redesign van magister - Denk aan IOS/Material design,
Willen jullie helpen met het PHP gedeelte? 
- Juul

**Comment by lesander** [comment]
Verkeerde repository? ;) https://github.com/simplyGits/Magister6.php

**Comment by lieuwex** [comment]
Duplicate of https://github.com/simplyGits/Magister6.php/issues/3
