### ISSUE TITLE
Fatal error: Uncaught Error: Non-static method mataphp\Mataphp::curlget() cannot be called statically

### ISSUE THREAD

**Issue by SmidtDeveloping** [DutchCodeGeeks/MATA-PHP#20]
Fatal error: Uncaught Error: Non-static method mataphp\Mataphp::curlget() cannot be called statically

**Comment by tomsmeding** [comment]
Warning: Uncaught DeprecationError: MATA-PHP is deprecated, MATA hasn't been online for nearly a decade
